
analysis_page <- function(id) {
  ns <- NS(id)
  div(
    titlePanel("Analysis Page"),
    p("Final Cash: ", textOutput(ns("cashValue"))),
    p("Final Emissions: ", textOutput(ns("emissionsValue"))),
    p("Final Score: ", textOutput(ns("finalScore"))),
    plotOutput(ns("summaryPlot"), height = "400px"),
    plotOutput(ns("cashBarPlot"), height = "400px"),
    plotOutput(ns("emissionsBarPlot"), height = "400px"),
    plotOutput(ns("solarBarPlot"), height = "400px"),
    actionButton(inputId = ns("back"), label = "Back to Home"),
    actionButton(inputId = ns("publish"), label = "Publish"),
  )
}


analysis_server <- function(id, gameData) {
  moduleServer(
    id,
    function(input, output, session) {
      ns <- session$ns
      
      observeEvent(input$back, change_page("/"))
      
      observe({
        data <- gameData()
        if (!is.null(data)) {
          game_state_df <- data$game_state
          final_cash <- data$final_cash
          final_emissions <- data$final_emissions
          final_score <- final_cash - final_emissions
          
          # Render cash and emissions values
          output$cashValue <- renderText({ paste("$", format(final_cash, big.mark = ",")) })  # formatted as currency
          output$emissionsValue <- renderText({ final_emissions })
          output$finalScore <- renderText({ final_score })
          
          # Ensure that there is data to work with
          # Plot cash, emissions, battery, and solar gained over the days
          output$summaryPlot <- renderPlot({
            plot(game_state_df$Day, game_state_df$Cash, type = "l", xlab = "Day", ylab = "", col = "green")
            lines(game_state_df$Day, game_state_df$Emissions, col = "red")
            lines(game_state_df$Day, game_state_df$Battery, col = "blue")
            lines(game_state_df$Day, game_state_df$SolarGained, col = "yellow")
            legend("topright", legend = c("Cash", "Emissions", "Battery", "Solar Gained"),
                   col = c("green", "red", "blue", "yellow"), lty = 1, cex = 0.8)
          })

          # Bar plot of total cash generated by each production line
          cash_generated <- colSums(game_state_df[, grep("CashGenerated", names(game_state_df))])
          output$cashBarPlot <- renderPlot({
            barplot(cash_generated, main = "Total Cash Generated by Each Production Line",
                    ylab = "Total Cash Generated", xlab = "Production Line")
          })

          # Bar plot of total emissions generated by each production line
          emissions_generated <- colSums(game_state_df[, grep("EmissionsGenerated", names(game_state_df))])
          output$emissionsBarPlot <- renderPlot({
            barplot(emissions_generated, main = "Total Emissions Generated by Each Production Line",
                    ylab = "Total Emissions Generated", xlab = "Production Line", col = "red")
          })

          # Bar plot of total solar consumption by each production line
          solar_consumed <- colSums(game_state_df[, grep("SolarConsumed", names(game_state_df))])
          output$solarBarPlot <- renderPlot({
            barplot(solar_consumed, main = "Total Solar Consumption by Each Production Line",
                    ylab = "Total Solar Consumed", xlab = "Production Line", col = "blue")
          })
        }
      })
      
      observeEvent(input$publish, {
        change_page("publish")
      })
      
      
    }
  )
}
